/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agendamatriz;

/**
 *
 * @author Pichau
 */
public class TelaCompromissos extends javax.swing.JFrame {

    /**
     * Creates new form TelaCompromissos
     */
    
    private OperacoesAgenda agenda = new OperacoesAgenda();
    
    public TelaCompromissos() {
        initComponents();
        agenda.CadastrarNovoAno(2021); // teste
        
        listaDeAnos.removeAllItems();
        String ano;
        
        for (int i = 0; i < this.agenda.TamanhoAgenda(); i++) {
            
        ano = Integer.toString(this.agenda.getAgenda().get(i).getAno());
        
        listaDeAnos.addItem(ano);
            
        }
                

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Titutlo = new javax.swing.JLabel();
        PainelAbas = new javax.swing.JTabbedPane();
        ConsultarCompromissos1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        painelConsulta = new javax.swing.JTabbedPane();
        Janeiro = new javax.swing.JScrollPane();
        tabelaJaneiro = new javax.swing.JTable();
        Fevereiro = new javax.swing.JScrollPane();
        tabelaFevereiro = new javax.swing.JTable();
        Março = new javax.swing.JScrollPane();
        tabelaMarço = new javax.swing.JTable();
        Abril = new javax.swing.JScrollPane();
        tabelaAbril = new javax.swing.JTable();
        Maio = new javax.swing.JScrollPane();
        tabelaMaio = new javax.swing.JTable();
        Junho = new javax.swing.JScrollPane();
        tabelaJunho = new javax.swing.JTable();
        Julho = new javax.swing.JScrollPane();
        tabelaJulho = new javax.swing.JTable();
        Agosto = new javax.swing.JScrollPane();
        tabelaAgosto = new javax.swing.JTable();
        Setembro = new javax.swing.JScrollPane();
        tabelaSetembro = new javax.swing.JTable();
        Outubro = new javax.swing.JScrollPane();
        tabelaOutubro = new javax.swing.JTable();
        Novembro = new javax.swing.JScrollPane();
        tabelaNovembro = new javax.swing.JTable();
        Dezembro = new javax.swing.JScrollPane();
        tabelaDezembro = new javax.swing.JTable();
        listaDeAnos = new javax.swing.JComboBox<>();
        Compromisso = new javax.swing.JLabel();
        selecioneAhora = new javax.swing.JLabel();
        listaDeHoras = new javax.swing.JComboBox<>();
        CadastrarCompromissos = new javax.swing.JPanel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextField1.setText("jTextField1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titutlo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Titutlo.setForeground(new java.awt.Color(255, 51, 51));
        Titutlo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titutlo.setText("Agenda de Compromissos");

        PainelAbas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PainelAbasMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Selecione o Ano:");

        tabelaJaneiro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1),  new Integer(2),  new Integer(3),  new Integer(4)},
                { new Integer(5),  new Integer(6),  new Integer(7),  new Integer(8)},
                { new Integer(9),  new Integer(10),  new Integer(11),  new Integer(12)},
                { new Integer(13),  new Integer(14),  new Integer(15),  new Integer(16)},
                { new Integer(17),  new Integer(18),  new Integer(19),  new Integer(20)},
                { new Integer(21),  new Integer(22),  new Integer(23),  new Integer(24)},
                { new Integer(25),  new Integer(26),  new Integer(27),  new Integer(28)},
                { new Integer(29),  new Integer(30),  new Integer(31), null}
            },
            new String [] {
                "Dia", "Dia", "Dia", "Dia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaJaneiro.setRowSelectionAllowed(false);
        tabelaJaneiro.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaJaneiro.getTableHeader().setReorderingAllowed(false);
        tabelaJaneiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaJaneiroMouseClicked(evt);
            }
        });
        Janeiro.setViewportView(tabelaJaneiro);
        tabelaJaneiro.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tabelaJaneiro.getColumnModel().getColumnCount() > 0) {
            tabelaJaneiro.getColumnModel().getColumn(0).setResizable(false);
            tabelaJaneiro.getColumnModel().getColumn(1).setResizable(false);
            tabelaJaneiro.getColumnModel().getColumn(2).setResizable(false);
            tabelaJaneiro.getColumnModel().getColumn(3).setResizable(false);
        }

        painelConsulta.addTab("Janeiro", Janeiro);

        tabelaFevereiro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1),  new Integer(2),  new Integer(3),  new Integer(4)},
                { new Integer(5),  new Integer(6),  new Integer(7),  new Integer(8)},
                { new Integer(9),  new Integer(10),  new Integer(11),  new Integer(12)},
                { new Integer(13),  new Integer(14),  new Integer(15),  new Integer(16)},
                { new Integer(17),  new Integer(18),  new Integer(19),  new Integer(20)},
                { new Integer(21),  new Integer(22),  new Integer(23),  new Integer(24)},
                { new Integer(25),  new Integer(26),  new Integer(27),  new Integer(28)},
                { new Integer(29),  new Integer(30),  new Integer(31), null}
            },
            new String [] {
                "Dia", "Dia", "Dia", "Dia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaFevereiro.setRowSelectionAllowed(false);
        tabelaFevereiro.getTableHeader().setReorderingAllowed(false);
        tabelaFevereiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaFevereiroMouseClicked(evt);
            }
        });
        Fevereiro.setViewportView(tabelaFevereiro);
        tabelaFevereiro.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tabelaFevereiro.getColumnModel().getColumnCount() > 0) {
            tabelaFevereiro.getColumnModel().getColumn(0).setResizable(false);
            tabelaFevereiro.getColumnModel().getColumn(1).setResizable(false);
            tabelaFevereiro.getColumnModel().getColumn(2).setResizable(false);
            tabelaFevereiro.getColumnModel().getColumn(3).setResizable(false);
        }

        painelConsulta.addTab("Fevereiro", Fevereiro);

        tabelaMarço.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1),  new Integer(2),  new Integer(3),  new Integer(4)},
                { new Integer(5),  new Integer(6),  new Integer(7),  new Integer(8)},
                { new Integer(9),  new Integer(10),  new Integer(11),  new Integer(12)},
                { new Integer(13),  new Integer(14),  new Integer(15),  new Integer(16)},
                { new Integer(17),  new Integer(18),  new Integer(19),  new Integer(20)},
                { new Integer(21),  new Integer(22),  new Integer(23),  new Integer(24)},
                { new Integer(25),  new Integer(26),  new Integer(27),  new Integer(28)},
                { new Integer(29),  new Integer(30),  new Integer(31), null}
            },
            new String [] {
                "Dia", "Dia", "Dia", "Dia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaMarço.setRowSelectionAllowed(false);
        tabelaMarço.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMarçoMouseClicked(evt);
            }
        });
        Março.setViewportView(tabelaMarço);
        tabelaMarço.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tabelaMarço.getColumnModel().getColumnCount() > 0) {
            tabelaMarço.getColumnModel().getColumn(0).setResizable(false);
            tabelaMarço.getColumnModel().getColumn(1).setResizable(false);
            tabelaMarço.getColumnModel().getColumn(2).setResizable(false);
            tabelaMarço.getColumnModel().getColumn(3).setResizable(false);
        }

        painelConsulta.addTab("Março", Março);

        tabelaAbril.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1),  new Integer(2),  new Integer(3),  new Integer(4)},
                { new Integer(5),  new Integer(6),  new Integer(7),  new Integer(8)},
                { new Integer(9),  new Integer(10),  new Integer(11),  new Integer(12)},
                { new Integer(13),  new Integer(14),  new Integer(15),  new Integer(16)},
                { new Integer(17),  new Integer(18),  new Integer(19),  new Integer(20)},
                { new Integer(21),  new Integer(22),  new Integer(23),  new Integer(24)},
                { new Integer(25),  new Integer(26),  new Integer(27),  new Integer(28)},
                { new Integer(29),  new Integer(30),  new Integer(31), null}
            },
            new String [] {
                "Dia", "Dia", "Dia", "Dia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaAbril.setRowSelectionAllowed(false);
        tabelaAbril.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaAbrilMouseClicked(evt);
            }
        });
        Abril.setViewportView(tabelaAbril);
        tabelaAbril.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tabelaAbril.getColumnModel().getColumnCount() > 0) {
            tabelaAbril.getColumnModel().getColumn(0).setResizable(false);
            tabelaAbril.getColumnModel().getColumn(1).setResizable(false);
            tabelaAbril.getColumnModel().getColumn(2).setResizable(false);
            tabelaAbril.getColumnModel().getColumn(3).setResizable(false);
        }

        painelConsulta.addTab("Abril", Abril);

        tabelaMaio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1),  new Integer(2),  new Integer(3),  new Integer(4)},
                { new Integer(5),  new Integer(6),  new Integer(7),  new Integer(8)},
                { new Integer(9),  new Integer(10),  new Integer(11),  new Integer(12)},
                { new Integer(13),  new Integer(14),  new Integer(15),  new Integer(16)},
                { new Integer(17),  new Integer(18),  new Integer(19),  new Integer(20)},
                { new Integer(21),  new Integer(22),  new Integer(23),  new Integer(24)},
                { new Integer(25),  new Integer(26),  new Integer(27),  new Integer(28)},
                { new Integer(29),  new Integer(30),  new Integer(31), null}
            },
            new String [] {
                "Dia", "Dia", "Dia", "Dia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaMaio.setRowSelectionAllowed(false);
        tabelaMaio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMaioMouseClicked(evt);
            }
        });
        Maio.setViewportView(tabelaMaio);
        tabelaMaio.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tabelaMaio.getColumnModel().getColumnCount() > 0) {
            tabelaMaio.getColumnModel().getColumn(0).setResizable(false);
            tabelaMaio.getColumnModel().getColumn(1).setResizable(false);
            tabelaMaio.getColumnModel().getColumn(2).setResizable(false);
            tabelaMaio.getColumnModel().getColumn(3).setResizable(false);
        }

        painelConsulta.addTab("Maio", Maio);

        tabelaJunho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1),  new Integer(2),  new Integer(3),  new Integer(4)},
                { new Integer(5),  new Integer(6),  new Integer(7),  new Integer(8)},
                { new Integer(9),  new Integer(10),  new Integer(11),  new Integer(12)},
                { new Integer(13),  new Integer(14),  new Integer(15),  new Integer(16)},
                { new Integer(17),  new Integer(18),  new Integer(19),  new Integer(20)},
                { new Integer(21),  new Integer(22),  new Integer(23),  new Integer(24)},
                { new Integer(25),  new Integer(26),  new Integer(27),  new Integer(28)},
                { new Integer(29),  new Integer(30),  new Integer(31), null}
            },
            new String [] {
                "Dia", "Dia", "Dia", "Dia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaJunho.setRowSelectionAllowed(false);
        tabelaJunho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaJunhoMouseClicked(evt);
            }
        });
        Junho.setViewportView(tabelaJunho);
        tabelaJunho.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tabelaJunho.getColumnModel().getColumnCount() > 0) {
            tabelaJunho.getColumnModel().getColumn(0).setResizable(false);
            tabelaJunho.getColumnModel().getColumn(1).setResizable(false);
            tabelaJunho.getColumnModel().getColumn(2).setResizable(false);
            tabelaJunho.getColumnModel().getColumn(3).setResizable(false);
        }

        painelConsulta.addTab("Junho", Junho);

        tabelaJulho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1),  new Integer(2),  new Integer(3),  new Integer(4)},
                { new Integer(5),  new Integer(6),  new Integer(7),  new Integer(8)},
                { new Integer(9),  new Integer(10),  new Integer(11),  new Integer(12)},
                { new Integer(13),  new Integer(14),  new Integer(15),  new Integer(16)},
                { new Integer(17),  new Integer(18),  new Integer(19),  new Integer(20)},
                { new Integer(21),  new Integer(22),  new Integer(23),  new Integer(24)},
                { new Integer(25),  new Integer(26),  new Integer(27),  new Integer(28)},
                { new Integer(29),  new Integer(30),  new Integer(31), null}
            },
            new String [] {
                "Dia", "Dia", "Dia", "Dia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaJulho.setRowSelectionAllowed(false);
        tabelaJulho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaJulhoMouseClicked(evt);
            }
        });
        Julho.setViewportView(tabelaJulho);
        tabelaJulho.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tabelaJulho.getColumnModel().getColumnCount() > 0) {
            tabelaJulho.getColumnModel().getColumn(0).setResizable(false);
            tabelaJulho.getColumnModel().getColumn(1).setResizable(false);
            tabelaJulho.getColumnModel().getColumn(2).setResizable(false);
            tabelaJulho.getColumnModel().getColumn(3).setResizable(false);
        }

        painelConsulta.addTab("Julho", Julho);

        tabelaAgosto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1),  new Integer(2),  new Integer(3),  new Integer(4)},
                { new Integer(5),  new Integer(6),  new Integer(7),  new Integer(8)},
                { new Integer(9),  new Integer(10),  new Integer(11),  new Integer(12)},
                { new Integer(13),  new Integer(14),  new Integer(15),  new Integer(16)},
                { new Integer(17),  new Integer(18),  new Integer(19),  new Integer(20)},
                { new Integer(21),  new Integer(22),  new Integer(23),  new Integer(24)},
                { new Integer(25),  new Integer(26),  new Integer(27),  new Integer(28)},
                { new Integer(29),  new Integer(30),  new Integer(31), null}
            },
            new String [] {
                "Dia", "Dia", "Dia", "Dia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaAgosto.setRowSelectionAllowed(false);
        tabelaAgosto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaAgostoMouseClicked(evt);
            }
        });
        Agosto.setViewportView(tabelaAgosto);
        tabelaAgosto.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tabelaAgosto.getColumnModel().getColumnCount() > 0) {
            tabelaAgosto.getColumnModel().getColumn(0).setResizable(false);
            tabelaAgosto.getColumnModel().getColumn(1).setResizable(false);
            tabelaAgosto.getColumnModel().getColumn(2).setResizable(false);
            tabelaAgosto.getColumnModel().getColumn(3).setResizable(false);
        }

        painelConsulta.addTab("Agosto", Agosto);

        tabelaSetembro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1),  new Integer(2),  new Integer(3),  new Integer(4)},
                { new Integer(5),  new Integer(6),  new Integer(7),  new Integer(8)},
                { new Integer(9),  new Integer(10),  new Integer(11),  new Integer(12)},
                { new Integer(13),  new Integer(14),  new Integer(15),  new Integer(16)},
                { new Integer(17),  new Integer(18),  new Integer(19),  new Integer(20)},
                { new Integer(21),  new Integer(22),  new Integer(23),  new Integer(24)},
                { new Integer(25),  new Integer(26),  new Integer(27),  new Integer(28)},
                { new Integer(29),  new Integer(30),  new Integer(31), null}
            },
            new String [] {
                "Dia", "Dia", "Dia", "Dia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaSetembro.setRowSelectionAllowed(false);
        tabelaSetembro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaSetembroMouseClicked(evt);
            }
        });
        Setembro.setViewportView(tabelaSetembro);
        tabelaSetembro.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tabelaSetembro.getColumnModel().getColumnCount() > 0) {
            tabelaSetembro.getColumnModel().getColumn(0).setResizable(false);
            tabelaSetembro.getColumnModel().getColumn(1).setResizable(false);
            tabelaSetembro.getColumnModel().getColumn(2).setResizable(false);
            tabelaSetembro.getColumnModel().getColumn(3).setResizable(false);
        }

        painelConsulta.addTab("Setembro", Setembro);

        tabelaOutubro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1),  new Integer(2),  new Integer(3),  new Integer(4)},
                { new Integer(5),  new Integer(6),  new Integer(7),  new Integer(8)},
                { new Integer(9),  new Integer(10),  new Integer(11),  new Integer(12)},
                { new Integer(13),  new Integer(14),  new Integer(15),  new Integer(16)},
                { new Integer(17),  new Integer(18),  new Integer(19),  new Integer(20)},
                { new Integer(21),  new Integer(22),  new Integer(23),  new Integer(24)},
                { new Integer(25),  new Integer(26),  new Integer(27),  new Integer(28)},
                { new Integer(29),  new Integer(30),  new Integer(31), null}
            },
            new String [] {
                "Dia", "Dia", "Dia", "Dia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaOutubro.setRowSelectionAllowed(false);
        tabelaOutubro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaOutubroMouseClicked(evt);
            }
        });
        Outubro.setViewportView(tabelaOutubro);
        tabelaOutubro.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tabelaOutubro.getColumnModel().getColumnCount() > 0) {
            tabelaOutubro.getColumnModel().getColumn(0).setResizable(false);
            tabelaOutubro.getColumnModel().getColumn(1).setResizable(false);
            tabelaOutubro.getColumnModel().getColumn(2).setResizable(false);
            tabelaOutubro.getColumnModel().getColumn(3).setResizable(false);
        }

        painelConsulta.addTab("Outubro", Outubro);

        tabelaNovembro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1),  new Integer(2),  new Integer(3),  new Integer(4)},
                { new Integer(5),  new Integer(6),  new Integer(7),  new Integer(8)},
                { new Integer(9),  new Integer(10),  new Integer(11),  new Integer(12)},
                { new Integer(13),  new Integer(14),  new Integer(15),  new Integer(16)},
                { new Integer(17),  new Integer(18),  new Integer(19),  new Integer(20)},
                { new Integer(21),  new Integer(22),  new Integer(23),  new Integer(24)},
                { new Integer(25),  new Integer(26),  new Integer(27),  new Integer(28)},
                { new Integer(29),  new Integer(30),  new Integer(31), null}
            },
            new String [] {
                "Dia", "Dia", "Dia", "Dia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaNovembro.setRowSelectionAllowed(false);
        tabelaNovembro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaNovembroMouseClicked(evt);
            }
        });
        Novembro.setViewportView(tabelaNovembro);
        tabelaNovembro.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tabelaNovembro.getColumnModel().getColumnCount() > 0) {
            tabelaNovembro.getColumnModel().getColumn(0).setResizable(false);
            tabelaNovembro.getColumnModel().getColumn(1).setResizable(false);
            tabelaNovembro.getColumnModel().getColumn(2).setResizable(false);
            tabelaNovembro.getColumnModel().getColumn(3).setResizable(false);
        }

        painelConsulta.addTab("Novembro", Novembro);

        tabelaDezembro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1),  new Integer(2),  new Integer(3),  new Integer(4)},
                { new Integer(5),  new Integer(6),  new Integer(7),  new Integer(8)},
                { new Integer(9),  new Integer(10),  new Integer(11),  new Integer(12)},
                { new Integer(13),  new Integer(14),  new Integer(15),  new Integer(16)},
                { new Integer(17),  new Integer(18),  new Integer(19),  new Integer(20)},
                { new Integer(21),  new Integer(22),  new Integer(23),  new Integer(24)},
                { new Integer(25),  new Integer(26),  new Integer(27),  new Integer(28)},
                { new Integer(29),  new Integer(30),  new Integer(31), null}
            },
            new String [] {
                "Dia", "Dia", "Dia", "Dia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaDezembro.setRowSelectionAllowed(false);
        tabelaDezembro.getTableHeader().setReorderingAllowed(false);
        tabelaDezembro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaDezembroMouseClicked(evt);
            }
        });
        Dezembro.setViewportView(tabelaDezembro);
        tabelaDezembro.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tabelaDezembro.getColumnModel().getColumnCount() > 0) {
            tabelaDezembro.getColumnModel().getColumn(0).setResizable(false);
            tabelaDezembro.getColumnModel().getColumn(1).setResizable(false);
            tabelaDezembro.getColumnModel().getColumn(2).setResizable(false);
            tabelaDezembro.getColumnModel().getColumn(3).setResizable(false);
        }

        painelConsulta.addTab("Dezembro", Dezembro);

        listaDeAnos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                listaDeAnosMouseMoved(evt);
            }
        });
        listaDeAnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaDeAnosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                listaDeAnosMouseEntered(evt);
            }
        });
        listaDeAnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaDeAnosActionPerformed(evt);
            }
        });

        Compromisso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        selecioneAhora.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        selecioneAhora.setText("Selecione a Hora:");

        listaDeHoras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));
        listaDeHoras.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                listaDeHorasMouseMoved(evt);
            }
        });
        listaDeHoras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaDeHorasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                listaDeHorasMouseEntered(evt);
            }
        });
        listaDeHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaDeHorasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConsultarCompromissos1Layout = new javax.swing.GroupLayout(ConsultarCompromissos1);
        ConsultarCompromissos1.setLayout(ConsultarCompromissos1Layout);
        ConsultarCompromissos1Layout.setHorizontalGroup(
            ConsultarCompromissos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultarCompromissos1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConsultarCompromissos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                    .addGroup(ConsultarCompromissos1Layout.createSequentialGroup()
                        .addGroup(ConsultarCompromissos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Compromisso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(ConsultarCompromissos1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(listaDeAnos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(selecioneAhora)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(listaDeHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        ConsultarCompromissos1Layout.setVerticalGroup(
            ConsultarCompromissos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultarCompromissos1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConsultarCompromissos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(listaDeAnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ConsultarCompromissos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(selecioneAhora)
                        .addComponent(listaDeHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Compromisso, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );

        PainelAbas.addTab("Consultar", ConsultarCompromissos1);

        javax.swing.GroupLayout CadastrarCompromissosLayout = new javax.swing.GroupLayout(CadastrarCompromissos);
        CadastrarCompromissos.setLayout(CadastrarCompromissosLayout);
        CadastrarCompromissosLayout.setHorizontalGroup(
            CadastrarCompromissosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );
        CadastrarCompromissosLayout.setVerticalGroup(
            CadastrarCompromissosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
        );

        PainelAbas.addTab("Cadastrar", CadastrarCompromissos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PainelAbas)
                    .addComponent(Titutlo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titutlo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelAbas)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaDeAnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaDeAnosActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_listaDeAnosActionPerformed

    private void listaDeAnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaDeAnosMouseClicked
        // TODO add your handling code here:
        
        
        
        
        
    }//GEN-LAST:event_listaDeAnosMouseClicked

    private void listaDeAnosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaDeAnosMouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_listaDeAnosMouseMoved

    private void PainelAbasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PainelAbasMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_PainelAbasMouseClicked

    private void listaDeAnosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaDeAnosMouseEntered
        // TODO add your handling code here:
        
        listaDeAnos.removeAllItems();
        String ano;
        
        for (int i = 0; i < this.agenda.TamanhoAgenda(); i++) {
            
        ano = Integer.toString(this.agenda.getAgenda().get(i).getAno());
        
        listaDeAnos.addItem(ano);
            
        }
        
        
    }//GEN-LAST:event_listaDeAnosMouseEntered

    private void tabelaJaneiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaJaneiroMouseClicked
        // TODO add your handling code here:
        
        Compromisso.setText(this.indexesToString());
        
    }//GEN-LAST:event_tabelaJaneiroMouseClicked
    
    private String indexesToString() {
        
        int ano,mes,dia,hora;
        
        dia = 13;
        
        switch (painelConsulta.getSelectedIndex()) {
            
            case 0:
                
                dia = tabelaJaneiro.getSelectedRow();
                break;
            
            case 1:
                
                dia = tabelaFevereiro.getSelectedRow();
                break;
                
            case 2:
                
                dia = tabelaMarço.getSelectedRow();
                break;
                
                
            case 3:
                
                dia = tabelaAbril.getSelectedRow();
                break;
                
                
            case 4:
                
                dia = tabelaMaio.getSelectedRow();
                break;
                
            case 5:
                
                dia = tabelaJunho.getSelectedRow();
                break;
                
            case 6:
                
                dia = tabelaJulho.getSelectedRow();
                break;
                
            case 7:
                
                dia = tabelaAgosto.getSelectedRow();
                break;
                
                
            case 8:
                
                dia = tabelaSetembro.getSelectedRow();
                break;
                
                
            case 9:
                
                dia = tabelaOutubro.getSelectedRow();
                break;
                
            case 10:
                
                dia = tabelaNovembro.getSelectedRow();
                break;
                
            case 11:
                
                dia = tabelaDezembro.getSelectedRow();
                break;    
            
        }
        
        ano = Integer.parseInt(listaDeAnos.getSelectedItem().toString());
        mes = painelConsulta.getSelectedIndex();
        System.out.println(mes);
        hora = listaDeHoras.getSelectedIndex();
        
        
        return this.agenda.ConsultaAgendaAnoMesDiaHora(ano,mes,dia,hora);
        
        
        
    }
    
    private void listaDeHorasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaDeHorasMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_listaDeHorasMouseMoved

    private void listaDeHorasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaDeHorasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_listaDeHorasMouseClicked

    private void listaDeHorasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaDeHorasMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_listaDeHorasMouseEntered

    private void listaDeHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaDeHorasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaDeHorasActionPerformed

    private void tabelaFevereiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaFevereiroMouseClicked
        // TODO add your handling code here:
        
        Compromisso.setText(this.indexesToString());
        
    }//GEN-LAST:event_tabelaFevereiroMouseClicked

    private void tabelaMarçoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMarçoMouseClicked
        // TODO add your handling code here:
        Compromisso.setText(this.indexesToString());
    }//GEN-LAST:event_tabelaMarçoMouseClicked

    private void tabelaAbrilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaAbrilMouseClicked
        // TODO add your handling code here:
        Compromisso.setText(this.indexesToString());
    }//GEN-LAST:event_tabelaAbrilMouseClicked

    private void tabelaMaioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMaioMouseClicked
        // TODO add your handling code here:
        Compromisso.setText(this.indexesToString());
    }//GEN-LAST:event_tabelaMaioMouseClicked

    private void tabelaJunhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaJunhoMouseClicked
        // TODO add your handling code here:
        Compromisso.setText(this.indexesToString());
    }//GEN-LAST:event_tabelaJunhoMouseClicked

    private void tabelaJulhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaJulhoMouseClicked
        // TODO add your handling code here:
        Compromisso.setText(this.indexesToString());
    }//GEN-LAST:event_tabelaJulhoMouseClicked

    private void tabelaAgostoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaAgostoMouseClicked
        // TODO add your handling code here:
        Compromisso.setText(this.indexesToString());
    }//GEN-LAST:event_tabelaAgostoMouseClicked

    private void tabelaSetembroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaSetembroMouseClicked
        // TODO add your handling code here:
        Compromisso.setText(this.indexesToString());
    }//GEN-LAST:event_tabelaSetembroMouseClicked

    private void tabelaOutubroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaOutubroMouseClicked
        // TODO add your handling code here:
        Compromisso.setText(this.indexesToString());
    }//GEN-LAST:event_tabelaOutubroMouseClicked

    private void tabelaNovembroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaNovembroMouseClicked
        // TODO add your handling code here:
        Compromisso.setText(this.indexesToString());
    }//GEN-LAST:event_tabelaNovembroMouseClicked

    private void tabelaDezembroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaDezembroMouseClicked
        // TODO add your handling code here:
        Compromisso.setText(this.indexesToString());
    }//GEN-LAST:event_tabelaDezembroMouseClicked
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCompromissos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCompromissos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCompromissos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCompromissos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCompromissos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Abril;
    private javax.swing.JScrollPane Agosto;
    private javax.swing.JPanel CadastrarCompromissos;
    private javax.swing.JLabel Compromisso;
    private javax.swing.JPanel ConsultarCompromissos1;
    private javax.swing.JScrollPane Dezembro;
    private javax.swing.JScrollPane Fevereiro;
    private javax.swing.JScrollPane Janeiro;
    private javax.swing.JScrollPane Julho;
    private javax.swing.JScrollPane Junho;
    private javax.swing.JScrollPane Maio;
    private javax.swing.JScrollPane Março;
    private javax.swing.JScrollPane Novembro;
    private javax.swing.JScrollPane Outubro;
    private javax.swing.JTabbedPane PainelAbas;
    private javax.swing.JScrollPane Setembro;
    private javax.swing.JLabel Titutlo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> listaDeAnos;
    private javax.swing.JComboBox<String> listaDeHoras;
    private javax.swing.JTabbedPane painelConsulta;
    private javax.swing.JLabel selecioneAhora;
    private javax.swing.JTable tabelaAbril;
    private javax.swing.JTable tabelaAgosto;
    private javax.swing.JTable tabelaDezembro;
    private javax.swing.JTable tabelaFevereiro;
    private javax.swing.JTable tabelaJaneiro;
    private javax.swing.JTable tabelaJulho;
    private javax.swing.JTable tabelaJunho;
    private javax.swing.JTable tabelaMaio;
    private javax.swing.JTable tabelaMarço;
    private javax.swing.JTable tabelaNovembro;
    private javax.swing.JTable tabelaOutubro;
    private javax.swing.JTable tabelaSetembro;
    // End of variables declaration//GEN-END:variables
}
